---
title: "EP"
---

## 

```{r}
library(readr)
```

```{r}
###funcion para redondear
r<-function(x){
  return(round(x,digits=2))
}

```


```{r}
DF<-read_csv("Twitch.csv")
```

```{r}
View(DF)

```




```{r}
#observaciones
nrow(DF)
#variables
ncol(DF)
#faltantes
sum(is.na(DF))
#incompletas
sum(!complete.cases(DF))

```


```{r}
#completos 
sum(complete.cases(DF))
# lo q se pierde en porcentaje 
round ( (sum(!complete.cases(DF)) / nrow(DF)) * 100, digits=2)



min(colSums(!is.na(DF)))

```


```{r}



DF$Juego <- factor(DF$Juego)
DF$Mes <- factor(DF$Mes, levels = c("Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"))


limpiar_num <- function(x) {
  as.numeric(gsub("[^0-9]", "", x))
}
DF$HorasV <- limpiar_num(DF$HorasV)
DF$HorasT <- limpiar_num(DF$HorasT)
DF$Streamers <- limpiar_num(DF$Streamers)
DF$MaxEsp <- limpiar_num(DF$MaxEsp)
DF$MaxCan <- limpiar_num(DF$MaxCan)
DF$PromEsp <- limpiar_num(DF$PromEsp)
DF$PromCan <- limpiar_num(DF$PromCan)


marzo_2023 <- subset(DF, Mes == "Marzo" & Año == 2023)

marzo_2023[which.max(marzo_2023$Pos), c("Juego", "Pos")]


```








```{r}
#tengo que hallas el coeficiente de variación
#tengo que hallar media mediana o moda 
#coef de variación
round ( sd(DF$HorasT, na.rm=TRUE) / mean(DF$HorasT, na.rm=TRUE), digits = 2)
#mediana 
median(DF$HorasT, na.rm=TRUE) 
```





Error en hist.default(DF$IndEC, prob = TRUE, main = "Histograma del número promedio de espectadores por canal", : 
  'x' debe ser numérico
  
  


```{r}
DF$IndEC <- DF$PromEsp / DF$PromCan
hist(DF$IndEC
     , prob = TRUE
     , main = "Histograma del número promedio de espectadores por canal"
     , ylim = c(-0.004, 0.025)
     , breaks = seq(0, 300, 10)
     , ylab = "densidad"
     , xlab = "promedio de espectadores por canal"
     , sub = paste("tamaño efectivo de la muestra:"
                   , sum(is.na(DF$IndEC))
                   , "reportes"
                   )
     )
boxplot(DF$IndEC
        , horizontal = TRUE
        , ann = FALSE
        , boxwex = 0.005
        , add = TRUE
        , at = -0.0025
        )
abline(v = mean(DF$IndEC, na.rm = TRUE), col = "red")
legend("topright"
       , legend = "promedio de IndEC"
       , col = "red"
       , bty = "n"
       , lty = 1
       )
```



```{r}
op <- par(mfrow = c(1, 2))
boxplot(DF$IndEC ~ DF$Año
        , las = 3
        , varwidth = TRUE
        , xlab = "año"
        , ylab = "espectadores por canal"
        )
boxplot(DF$PromCan ~ DF$Año
        , log = "y"
        , las = 3
        , varwidth = TRUE
        , xlab = "año"
        , ylab = "canales"
        , ylim = c(1, 10000)
        , ylab = c(1, 10000, 1)
        )
par(op)
title(main = "Espectadores por canal y número de canales a lo largo del tiempo")

```











